/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all projects
         * @description Returns a paginated list of all projects.
         */
        get: operations["listProjects"];
        put?: never;
        /**
         * Create a new project
         * @description Creates a new project with the provided details.
         */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project by ID
         * @description Returns a single project by its unique identifier.
         */
        get: operations["getProject"];
        /**
         * Update a project
         * @description Updates an existing project with the provided details.
         */
        put: operations["updateProject"];
        post?: never;
        /**
         * Delete a project
         * @description Permanently deletes a project and all associated data.
         */
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        /**
         * Partially update a project
         * @description Updates specific fields of an existing project. Only provided fields are updated.
         */
        patch: operations["patchProject"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Project: {
            /** @description Unique identifier (UUID or cuid2 format) */
            id: string;
            /** @description Project name */
            name: string;
            /** @description Optional project description */
            description?: string | null;
            /** @description Project-specific settings */
            settings?: {
                [key: string]: unknown;
            };
            /**
             * Format: date-time
             * @description ISO 8601 timestamp
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp
             */
            updatedAt: string;
        };
        CreateProject: {
            /** @description Project name (required) */
            name: string;
            /** @description Optional project description */
            description?: string;
            /** @description Project-specific settings */
            settings?: {
                [key: string]: unknown;
            };
        };
        UpdateProject: {
            /** @description New project name */
            name?: string;
            /** @description New project description */
            description?: string;
            /** @description Project-specific settings */
            settings?: {
                [key: string]: unknown;
            };
        };
        PaginationMeta: {
            /** @description Current page number */
            page: number;
            /** @description Items per page */
            limit: number;
            /** @description Number of items in current page */
            count: number;
            /** @description Total number of items */
            total?: number;
            /** @description Whether more pages exist */
            hasMore: boolean;
        };
        /**
         * @description Machine-readable error code
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "INVALID_INPUT" | "MISSING_REQUIRED_FIELD" | "INVALID_FORMAT" | "NOT_FOUND" | "ALREADY_EXISTS" | "INVALID_ID" | "LIMIT_EXCEEDED" | "INVALID_STATE" | "OPERATION_NOT_ALLOWED" | "UNAUTHORIZED" | "FORBIDDEN" | "INVALID_TOKEN" | "TOKEN_EXPIRED" | "FILE_TOO_LARGE" | "INVALID_FILE_TYPE" | "INVALID_MAGIC_BYTES" | "FILE_NOT_FOUND" | "SYMLINK_NOT_ALLOWED" | "PATH_TRAVERSAL" | "SERVICE_UNAVAILABLE" | "TIMEOUT" | "INTERNAL_ERROR" | "DATABASE_ERROR" | "EXTERNAL_SERVICE_ERROR" | "RATE_LIMIT_EXCEEDED";
        Error: {
            error: {
                /** @description Human-readable error message */
                message: string;
                code: components["schemas"]["ErrorCode"];
                /** @description Additional error context */
                details?: {
                    [key: string]: unknown;
                };
            };
            /** @description Unique request identifier for debugging */
            requestId: string;
            /**
             * Format: date-time
             * @description ISO 8601 timestamp of the error
             */
            timestamp: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProjects: {
        parameters: {
            query?: {
                /** @description Page number (1-indexed) */
                page?: number;
                /** @description Items per page (max 100) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["Project"][];
                        pagination: components["schemas"]["PaginationMeta"];
                    };
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProject"];
            };
        };
        responses: {
            /** @description Project created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID (UUID or cuid2) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Invalid ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID (UUID or cuid2) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProject"];
            };
        };
        responses: {
            /** @description Project updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Invalid ID format or validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID (UUID or cuid2) */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project deleted successfully */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid ID format */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    patchProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Project ID (UUID or cuid2) */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProject"];
            };
        };
        responses: {
            /** @description Project updated successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Invalid ID format or validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Project not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
